version: "3.3"

services:
  app:
    container_name: "service-api"
    build:
      context: "."
    env_file: .env
#    command: gunicorn --bind 0.0.0.0:5000 manage:app
    command:
      - /bin/sh
      - -c
      - |
        echo "Waiting database"
        sleep 12
        python manage.py runserver
    volumes:
      - .:/usr/app/
    depends_on:
      - database
    ports:
      - "5000:5000"
  database:
    image: mysql:5.6
    container_name: "service-db"
    restart: always
    command: --init-file /docker-entrypoint-initdb.d/setup.sql
    environment:
      MYSQL_ROOT_PASSWORD: v25xhycLlRY3sV7Z
      MYSQL_DATABASE: "exercise"
    volumes:
      - ./database/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
